// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Command Prisma runs for `prisma db seed`. `tsx` executes the TypeScript
    // seed file directly without a separate compile step.
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI commands (`db push`, `db seed`) perform schema DDL, which is
    // unreliable over Neon's PgBouncer pooler. Use the DIRECT (unpooled) URL
    // when provided, falling back to DATABASE_URL for local/dev setups that
    // have no separate pooler endpoint. The app RUNTIME always uses the pooled
    // DATABASE_URL (see src/lib/prisma.ts) — this override is CLI-only.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
