// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load env for CLI commands (db push / seed) the same way Next.js does at
// runtime: `.env` first, then `.env.local` overriding it. Without the second
// call the Prisma CLI would miss vars placed only in `.env.local`.
config();
config({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Command Prisma runs for `prisma db seed`. `tsx` executes the TypeScript
    // seed file directly without a separate compile step.
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI commands (`db push`, `db seed`) perform schema DDL, which is
    // unreliable over Neon's PgBouncer pooler. Use the DIRECT (unpooled) URL
    // when provided, falling back to DATABASE_URL for local/dev setups that
    // have no separate pooler endpoint. The app RUNTIME always uses the pooled
    // DATABASE_URL (see src/lib/prisma.ts) — this override is CLI-only.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
